### ISSUE TITLE
Issues found when running through instructions

### ISSUE THREAD

**Issue by okwme** [allinbits/cosm#2]
`cosm start` doesn't seem to work. I get the following error:
```sh
> cosm start
Error: unknown command "start" for "cosmos"
Run 'cosmos --help' for usage.
unknown command "start" for "cosmos"
```

---

After running `cosm app <repo>` I see the word "token" printed on the screen. Is this on purpose?

---

I tried following the type instructions by making a new type:
```sh
> cosm type foo bar

🎉 Created a type `foo`.
```
It seemed to work correctly but when I tried to create a transaction with the new type following the example i got an account error:
```sh
> testcli tx test create-foo "foobar" --from=me
ERROR: unknown address: account cosmos1n0drc7wcq3xk5rjsp6dat99tl7jxfr2jlyntzn does not exist
```
(my project is called "test")

---

I started up the UI but I see an error in the console:

```sh
> npm run serve

> ui@1.0.0 preserve /Users/billy/GitHub.com/okwme/test/ui
> lcp --proxyUrl http://localhost:1317 &


> ui@1.0.0 serve /Users/billy/GitHub.com/okwme/test/ui
> parcel index.html


 Proxy Active

Proxy Url: http://localhost:1317
Proxy Partial: proxy
PORT: 8010
Credentials: false
Origin: *

To start using the proxy simply replace the proxied part of your url with: http://localhost:8010/proxy

Server running at http://localhost:1234
✨  Built in 11.54s.
Request Proxied -> /test/foo
Request Proxied -> /faucet
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

Error: socket hang up
    at connResetException (internal/errors.js:608:14)
    at Socket.socketOnEnd (_http_client.js:453:23)
    at Socket.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ECONNRESET'
}
```
In the browser I see the interface show up and I seem to be able to generate new accounts but there's an error in the dev console and another one appear when i click faucet:
```sh
xhr.js:178 GET http://localhost:8010/proxy/test/foo net::ERR_CONNECTION_REFUSED
dispatchXhrRequest @ xhr.js:178
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:52
Promise.then (async)
request @ Axios.js:61
Axios.<computed> @ Axios.js:76
wrap @ bind.js:9
fetchList @ script.js:57
(anonymous) @ script.js:49
init @ script.js:46
parcelRequire.script.js.axios @ script.js:108
newRequire @ script.75da7f30.js:47
(anonymous) @ script.75da7f30.js:81
(anonymous) @ script.75da7f30.js:120
createError.js:16 Uncaught (in promise) Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:83)
createError @ createError.js:16
handleError @ xhr.js:83
Promise.then (async)
fetchList @ script.js:57
(anonymous) @ script.js:49
init @ script.js:46
parcelRequire.script.js.axios @ script.js:108
newRequire @ script.75da7f30.js:47
(anonymous) @ script.75da7f30.js:81
(anonymous) @ script.75da7f30.js:120
script.js:26 Uncaught TypeError: Cannot read property 'address' of undefined
    at HTMLButtonElement.requestTokens (script.js:26)
requestTokens @ script.js:26
```
---
Not to say that this isn't AMAZING, these features are already so far beyond what is currently available with scaffolding a new application SO FREAKING COOL!!!

**Comment by fadeev** [comment]
@okwme thanks! This is so useful! I'm fixing all of these things now 🙂

**Comment by fadeev** [comment]
`cosm start` used to be a command before I got hot-reloading to work properly. I'll probably add a flag to disable reloading. Removed reference to `cosm start` from readme.

`token` 😄 Yeah, you can customize denom with `-d` flag and this is me testing that it works with `Println`. Removed.

https://twitter.com/codewisdom/status/1248590807562584064 — I should paid more attention to the first part of this sentence.

And the "biggest" issue is the silliest. I literally had `blogd` hardcoded in `cosm serve`, so no matter what, it runs `blogd` command because that's what I used for testing. I've replaced it with `fmt.Sprintf("%[1]vd", appName)`.

Thanks again! Feedback such as this is invaluable!
